### ISSUE TITLE
More how to use it

### ISSUE THREAD

**Issue by k3rps** [jpbede/pygrundig#1]
Hi, would be nice if you could explain more how it works.
Tried with my grundig tv ip but got False back, and where did you get the keycodes? :)

**Comment by k3rps** [comment]
It kinda works now, I know for sure it communicates with the tv but nothing happens except I get a popup window and it says in german "startleiste. Das Erste. Datenschutzhinweise", so something about privacy policy. Do you have any idea what it could be?

**Comment by GreenSnakeLinux** [comment]
If you accept the 'policy text' on the pop up or in TV settings does it appear again ?

I would like also more keycodes, thanks
